// ============================================================================
// ai-init — Generates questionnaire questions and color palettes for a new
// project, based on the user's business idea.
// Uses: openai/gpt-oss-120b:free via OpenRouter.
//
// NOTE: Design styles are NO LONGER generated by the AI. The frontend shows
// all 10 styles to the user directly. This removes a failure point and gives
// users full control.
// ============================================================================
import { corsHeaders, json, errorJson, callOpenRouter, extractJSON } from "../_shared/cors.ts";

const INIT_SYSTEM_PROMPT = `You are Clay, an AI helping a non-technical user build their first website. Based on their business idea, generate a questionnaire and color palettes.

Output ONLY valid JSON. No markdown, no prose, no code fences. Use this exact shape:

{"name":"string","tagline":"string","questions":[{"id":"snake_case","question":"string","help_text":"string","options":["str","str","str"],"default":"str","multi_select":false}],"color_palettes":[{"name":"string","colors":["#bg","#primary","#secondary","#accent","#text"]}]}

RULES:

== NAME GENERATION — CRITICAL ==
The "name" must be a CREATIVE, BRANDABLE name — NOT a description of the business.
- BAD (descriptive, boring): "AI Tutor Hub", "AI Web Tutors", "Bakery Shop", "Yoga Studio", "Tutoring Services", "Web Dev Academy"
- GOOD (brandable, memorable): "Promptly", "Crust & Crumb", "Asana House", "Codecraft", "Bakehaus", "Flowstate"
Rules:
- 1-2 words, max 3
- No generic suffixes: "Hub", "Services", "Center", "Studio", "Academy", "Tutors", "Shop", "Co" — UNLESS it's genuinely part of a creative brand name
- Coin a new word, use a metaphor, or combine unexpected words
- Do NOT include the business type in the name (no "Tutor", "Bakery", "Yoga" unless it's part of a creative coinage)

== REDUNDANT QUESTIONS — CRITICAL ==
Read the business idea carefully. Do NOT ask about ANYTHING the user already stated. Common things users mention:
- Target audience (age, profession, demographic)
- Core service or product
- Location
- Specialty or differentiator
Example: If the user writes "I tutor high school students aged 15-18 in using AI for web development", you must NOT ask "who is your audience" or "what is your main service" — those are answered. Only ask about things NOT mentioned.

== MULTI-SELECT — CRITICAL ==
Any question where multiple answers make sense MUST have "multi_select": true. The options must be INDIVIDUAL choices, NOT pre-combined bundles.

WRONG (single-select with bundled options):
  "question": "What contact details do you want to display?"
  "options": ["Email only", "Phone & Email", "WhatsApp & Email"]
  "multi_select": false

CORRECT (multi-select with individual options):
  "question": "What contact details do you want to display? (Select all that apply)"
  "options": ["Email", "Phone", "WhatsApp", "Contact form", "Address"]
  "default": ["Email", "Contact form"]
  "multi_select": true

Always use multi-select for:
- Which sections to include (Home, About, Services, etc.)
- What contact methods to display
- What features to include
- What social media links to show

For multi_select: phrase the question with "(Select all that apply)", make "default" an array, and NEVER include "All of the above" as an option.

Single-select (multi_select:false) is for: navigation style, tone of voice, call-to-action focus.

== QUESTIONS TO ASK (4-6 total, only about unspecified things) ==
Always include:
1. Navigation style (single-select: Top-bar, Sidebar, optionally Mega-menu for large sites)
2. Sections to include (MULTI-SELECT: Home, About, Services, Pricing, Testimonials, Contact, Blog, FAQ, Gallery, Team)
3. Tone of voice (single-select)
Then add 1-3 more only if the business idea doesn't already cover them.

== COLOR PALETTES (4 total) ==
Each palette: 5 uppercase hex codes (#RRGGBB) in order: background, primary, secondary, accent, text. Tailor to the business.

== JSON ESCAPING ==
ALL double-quotes inside string values MUST be escaped as \\". ALL backslashes as \\\\. Output ONLY the JSON object.`;

const INIT_USER_TEMPLATE = (idea: string, name: string | null) => `Business idea: """${idea}"""
Project name: ${name && name.trim() ? `"""${name.trim()}"""` : "(none — generate a creative brandable name)"}

Generate the JSON now. Remember: do not ask about anything already stated in the business idea. Use multi_select:true with individual options (not bundled) for any question where multiple answers make sense.`;

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }
  try {
    const body = await req.json();
    const idea = body?.idea;
    const name = body?.name ?? null;
    if (!idea || typeof idea !== "string" || idea.trim().length < 5) {
      return errorJson("Missing or too-short 'idea'.", 400);
    }

    const apiKey = Deno.env.get("OPENROUTER_API_KEY");
    if (!apiKey) return errorJson("OPENROUTER_API_KEY secret not set. Add it in Supabase → Edge Functions → Secrets.", 500);

    const messages = [
      { role: "system", content: INIT_SYSTEM_PROMPT },
      { role: "user", content: INIT_USER_TEMPLATE(idea, name) },
    ];

    let lastError = "";

    for (let attempt = 0; attempt < 3; attempt++) {
      let raw: string;
      try {
        raw = await callOpenRouter(
          apiKey,
          "openai/gpt-oss-120b:free",
          messages,
          { temperature: attempt === 0 ? 0.85 : 0.5, max_tokens: 16000 }
        );
      } catch (e) {
        lastError = String(e?.message || e);
        console.warn(`[ai-init] Attempt ${attempt + 1} API error: ${lastError}`);
        if (attempt < 2) await sleep(2000);
        continue;
      }

      if (!raw || !raw.trim()) {
        lastError = "Empty response from model.";
        if (attempt < 2) await sleep(2000);
        continue;
      }

      let parsed;
      try {
        parsed = extractJSON(raw);
      } catch (parseErr) {
        lastError = String(parseErr?.message || parseErr);
        console.warn(`[ai-init] Attempt ${attempt + 1} parse error: ${lastError}`);
        if (attempt < 2) await sleep(1500);
        continue;
      }

      if (!parsed.questions || !Array.isArray(parsed.questions) || !parsed.color_palettes) {
        lastError = "Missing required fields (questions or color_palettes).";
        if (attempt < 2) await sleep(1500);
        continue;
      }

      // Normalize multi_select + default on each question.
      // Strip "All of the above" options. Force multi_select for certain patterns.
      parsed.questions = (parsed.questions || []).map((q: any) => {
        let multi = q.multi_select === true;
        let options = (q.options || []).filter((o: string) =>
          !/^(all of the above|all of these|all options|none of the above)$/i.test(String(o).trim())
        );
        // Force multi_select based on question content
        const qLower = String(q.question || '').toLowerCase();
        if (/select all|sections|features|contact (details|methods|options)|social media|which pages|what pages/i.test(qLower)) {
          multi = true;
        }
        let def = q.default;
        if (multi) {
          if (!Array.isArray(def)) {
            def = def ? [def] : (options.length ? [options[0]] : []);
          }
        } else {
          if (Array.isArray(def)) def = def[0] || (options[0] || "");
        }
        return { ...q, options, multi_select: multi, default: def };
      });

      // Design styles are no longer from the AI — always return all 10
      parsed.design_styles = ["minimalism","brutalism","swiss","neumorphism","editorial","glassmorphism","art-deco","corporate","playful","organic"];

      return json(parsed);
    }

    return errorJson(
      "The AI model couldn't generate a valid response after 3 attempts. This is usually due to rate-limiting on the free tier — please wait 10 seconds and try again. Last error: " + lastError,
      502
    );
  } catch (e) {
    return errorJson("Server error: " + String(e?.message || e), 500);
  }
});
